apiVersion: v1
name: mysql
version: 1.0.0
appVersion: 5.7.30
description: local version of mysql enabling config for  arm64 
  system.
keywords:
- mysql
- database
- sql
home: https://www.mysql.com/
icon: https://www.mysql.com/common/logos/logo-mysql-170x115.png
sources:
- https://github.com/kubernetes/charts
- https://github.com/docker-library/mysql
deprecated: true
engine: gotpl
