# requirements.yaml
dependencies:
# - name: kafka
#   version: 0.21.2
#   repository: https://charts.helm.sh/incubator
#   alias: kafka
#   condition: kafka.enabled
- name: mongodb
  version: 7.8.10
  repository: https://charts.bitnami.com/bitnami/
  alias: mongodb
  condition: mongodb.enabled
