apiVersion: v1
description: locally modified version of the deprecated incubator chart.
  commit log.
name: kafka
version: 1.0.0
appVersion: 5.0.1
keywords:
- kafka
- zookeeper
- kafka statefulset
home: https://kafka.apache.org/
sources:
- https://github.com/kubernetes/charts/tree/master/incubator/zookeeper
- https://github.com/Yolean/kubernetes-kafka
- https://github.com/confluentinc/cp-docker-images
- https://github.com/apache/kafka
deprecated: true
icon: https://kafka.apache.org/images/logo.png
